version: 1.0.{build}

environment:
    matrix:
      - BUILDER: build_msvc
        CPU:     x86
      - BUILDER: build_msvc
        CPU:     x64
      - BUILDER: build_mingw
        CPU:     x86
   #  - BUILDER: build_mingw
   #    CPU:     x64

build_script:
  - cmd: appveyor-script.bat init
  - cmd: appveyor-script.bat %BUILDER% %CPU%

test_script:
  - cmd: set DUMP_MODULES=0
  - cmd: set WSOCK_TRACE_LEVEL=1 & test.exe
  - cmd: set WSOCK_TRACE_LEVEL=0 & chcp 865 & idna.exe              www.seoghør.no
  - cmd: set WSOCK_TRACE_LEVEL=0 &            idna.exe -c1252 -wddd www.seoghør.no

