version: 1.0.{build}

environment:
    matrix:
      - BUILDER: build_msvc
        CPU:     x86
      - BUILDER: build_msvc
        CPU:     x64
      - BUILDER: build_mingw
        CPU:     x86
   #  - BUILDER: build_mingw
   #    CPU:     x64

build_script:
  - cmd: appveyor-script.bat init
  - cmd: appveyor-script.bat %BUILDER% %CPU%
