version: 1.0.{build}

#
# Skipping commits affecting these files
#
skip_commits:
   files:
    - '**/*.md'
    - '**/*.png'
    - '**/*.jpg'

#
# setting up etc\hosts file
# XXX - use this instead of batch file generated one
#
hosts:
  localhost: 127.0.0.1
# localhost: ::1 # appveyor doesn't like "duplicates"
  mpa.one.microsoft.com: 127.0.0.1
  google-public-dns-a.google.com: 8.8.8.8
  www.no-such-host.com: 10.0.0.20

environment:
  global:
    # CFLAGS: '-Wall --coverage'
    # LDFLAGS: '-lgcov --coverage'
    CL: /nologo /MP
  matrix:
    - BUILDER: msvc
      CPU:     x86
    - BUILDER: msvc
      CPU:     x64
    - BUILDER: mingw
      CPU:     x86
      MSYSTEM: MINGW32
    - BUILDER: mingw
      CPU:     x64
      MSYSTEM: MINGW64
#   - BUILDER: cygwin
#     CPU:     x64

matrix:
#
# Immediately finish build if one of the above jobs fails.
#
  fast_finish: true
  allow_failures:
    - BUILDER: cygwin
      CPU:     x64

#
# XXX - WIP
# Get better version string. Maybe output of "git describe --tags --long"
#
cache:
  - wsock-trace-{build}

install:
  # clone the submodules
  - cmd: git submodule update --init --recursive

  # add a few locations to our path
  - cmd: set PATH=%CD%\src;%PATH%
  - cmd: if "%BUILDER%"=="mingw"  set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
  - cmd: if "%BUILDER%"=="cygwin" set PATH=C:\msys64\usr\bin;%PATH%

  # set compiler environment
  - cmd: if "%BUILDER%"=="msvc" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%CPU%

  # Download COUNTRY Database.
  # XXX - Encrypt URL! See https://www.appveyor.com/docs/build-configuration/#secure-variables
  - cmd: appveyor DownloadFile http://www.watt-32.net/CI/IP4-COUNTRY.BIN.xz
  - cmd: 7z.exe x IP4-COUNTRY.BIN.xz > NUL

build_script:
  - cmd: appveyor-script.bat init
  - cmd: cd src
  - cmd: if "%BUILDER%"=="msvc"   nmake -nologo -f Makefile.vc6 USER=AppVeyor USE_LUA=1 USE_IP2LOCATION=1 CPU=%CPU% PLATFORM=%CPU%
  - cmd: if "%BUILDER%"=="mingw"  make -f Makefile.MinGW        USER=AppVeyor USE_LUA=1 USE_IP2LOCATION=1 CPU=%CPU%
  - cmd: if "%BUILDER%"=="cygwin" make -f Makefile.CygWin       USER=AppVeyor USE_LUA=1 USE_IP2LOCATION=1 CPU=%CPU%

test_script:
  - cmd: set WSOCK_TRACE_LEVEL=2 & test.exe
  - cmd: set WSOCK_TRACE_LEVEL=0 & chcp 865 & idna.exe              www.seoghør.no
  - cmd: set WSOCK_TRACE_LEVEL=0 &            idna.exe -c1252 -wddd www.seoghør.no

artifacts:
#
# Needed for cross-compiling
#
  - path: 'src\geoip-gen*.c'
# To push all *.zip/exe... files.
  - path: '**\*.dll'
  - path: '**\*.lib'
  - path: '**\*.a'
  - path: '**\*.exe'
#
# WIP: Push the entire wsock-trace-{build} folder as a single zip archive.
#
  - path: wsock-trace-{build}

#
# XXX - One day...
#
# deploy:
  # Deploying to NuGet feed
  # - provider: NuGet
    # server: https://my.nuget.server/feed
    # api_key:
      # secure: FYWX6NfjZIVw==
    # skip_symbols: false
    # symbol_server: https://your.symbol.server/feed
    # artifact: MyPackage.nupkg

  # Deploy to GitHub Releases
  # - provider: GitHub
    # artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    # draft: false
    # prerelease: false
    # on:
      # branch: master                # release from master branch only
      # appveyor_repo_tag: true       # deploy on tag push only
