version: 1.0.{build}

environment:
    matrix:
      - BUILDER: msvc
        CPU:     x86
      - BUILDER: msvc
        CPU:     x64
      - BUILDER: mingw
        CPU:     x86
    # - BUILDER: mingw
    #   CPU:     x64

install:
  # clone the submodules
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: appveyor-script.bat init
  - cmd: appveyor-script.bat %BUILDER% %CPU%

test_script:
  - cmd: set WSOCK_TRACE_LEVEL=2 & test.exe
  - cmd: set WSOCK_TRACE_LEVEL=0 & chcp 865 & idna.exe              www.seoghør.no
  - cmd: set WSOCK_TRACE_LEVEL=0 &            idna.exe -c1252 -wddd www.seoghør.no

